% -*- matlab-ts -*-

% t-utils-test-indent: no-line-by-line-indent - when we type line-by-line, we don't see later lines

for wIndex = 1:length(foo.blah)
    fooBarGooToo = [something                                ...
        [otherThing(wIndex):theEndIndex(wIndex)-1                     ...
          otherThing(wIndex)+1:theEndIndex(wIndex);                     ...
        otherThing(wIndex)+1:theEndIndex(wIndex)                      ...
        otherThing(wIndex):theEndIndex(wIndex)-1]]; %#ok<AGROW>
    P0 = [P0 foo.blah{wIndex}.foobarGooOrig(:,1:end-1)]; %#ok<AGROW>
    P1 = [P1 foo.blah{wIndex}.foobarGooOrig(:,2:end)]; %#ok<AGROW>
end


for wIndex = 1:length(foo.blah)
    fooBarGooToo = [something                                ...
        {otherThing(wIndex):theEndIndex(wIndex)-1                     ...
          otherThing(wIndex)+1:theEndIndex(wIndex);                     ...
        otherThing(wIndex)+1:theEndIndex(wIndex)                      ...
        otherThing(wIndex):theEndIndex(wIndex)-1}]; %#ok<AGROW>
    P0 = [P0 foo.blah{wIndex}.foobarGooOrig(:,1:end-1)]; %#ok<AGROW>
    P1 = [P1 foo.blah{wIndex}.foobarGooOrig(:,2:end)]; %#ok<AGROW>
end
