% -*- matlab-ts -*-

% Notice the extra statements after the matrix. For simplicity we require 'non-numeric-m-matrix
% classification to have the matrix defined in it's ownline and not shared with other language
% items.

a = 1;
foo = 2;

notMat1 = [ ...
       1,   a+ foo*2; ...
    333, 4; ...
       ]; if 1, disp('here')
          end

notMat2 = [ ...
       1,   a+ foo*2; ...
    333, 4; ...
       ];  mat3 = [ ...
       1,   a+ foo*2; ...
    333, 4; ...
       ]; 
