% -*- matlab-ts -*-

% t-utils-test-indent: no-line-by-line-indent - need valid parse to see the hidden comma after 'two'

foo1 = {'one', 'two', ...
        'three', 'four', 'five'};

foo2 = {'one', 'two', ...
        ...
        'three', 'four', 'five'};

foo3 = {'one', 'two' ...
        , ...
        'three', 'four', 'five'};

foo4 = {'one', 'two' ...
        ...
        , 'three', 'four', 'five'};

% Following is a 2x3 matrix. The blank line makes a column.

foo5 = ["foo", "two", "three", ...

        "four", "five", "six"];

% Following shouldn't add a comma within the fullfile, i.e. the continuation is not part of the
% matrix
b = '/one/two';
v1 = {['a', fullfile(b, ...
                     'foo'), ['a', ...
                              'b']], {1, ...
                                      2}};
disp(v1)
