% -*- matlab-ts -*-

% t-utils-test-indent: no-line-by-line-indent - line-by-line typing results in error nodes

if 1
    s1 = struct('field1',      value1 + 10, ...
                ...
                'otherfield2', value2);
end

s2 = struct('field1',      value1, ...
            'otherfield2', value2)

a(1, 1) = struct('field1',      value1, ...
                 'otherfield2', value2)

a(1, 2) = struct( ...
    'field1',      value1, ...
    'otherfield2', value2, ...
    'foo',         1 + 2 * 3)

s3 = struct( ...
    'field1',      value1, ...
    'otherfield2', value2);

s4 = struct( ...
    'longField1', value1, ...
    'field2',     value2)

s5 = struct("a",      1, ...
            ...
            "foobar", (2 + 3) * 4 + 5, ...
            "g",      3);

not1 = struct('one', value1, 'two', value2, ...
              'three', value3);

not2 = struct(['field1', 'foo'], value1 + 10, ...
              ...
              'otherfield2', value2);

% Comma in field name not allowed because that isn't supported (yet) by matlab-ts-mode--ei.el
% In matlab-ts-mode--ei.el, we assume (string-match-p "," ei-line open-paren-offset) goes
% to the comma after the first field. To support fields with commas in the name, we'll need
% to do more work and commas are a real edge case.
not3 = struct('field1,foo', value1 + 10, ...
              ...
              'otherLongField2', value2);

not5 = struct ...
    ('field1', 1, ...
     'longField2', 2);

not6 = ...
    struct ...
        ('field1', 1, ...
         'lognField2', 2);

not7 ...
    = ...
    struct ...
        ('field1', 1, ...
         'longField2', 2);

not8 = struct; % (this shouldn't be aligned!
