% -*- matlab-ts -*-

% t-utils-test-indent: no-line-by-line-indent - line-by-line typing results in error nodes

foobar = struct('type',    {'one', 'two', ...
                            'three', 'four'}, ...
                'fooport', {1, 2, 3, 4, 4, 4, 4, 4, 4, 1, 2}, ...
                't',       1, ...
                'x',       struct('a', 1, ...
                                  'foo', 10));
