% -*- matlab-ts -*-

% Notice the extra statements after the matrix. For simplicity we require 'numeric-m-matrix
% classification to have the matrix defined in it's ownline and not shared with other language
% items.

notMat1 = [ ...
       1,   2222; ...
    333, 4; ...
       ]; if 1, disp('here')
          end

notMat2 = [ ...
       1,   2222; ...
    333, 4; ...
       ];  mat3 = [ ...
       1,   2222; ...
    333, 4; ...
       ]; 
