# File: doc/remote-matlab-shell.org

#+startup: showall
#+options: toc:nil

# Copyright 2025 Free Software Foundation, Inc.

The [[https://github.com/mathworks/MATLAB-language-server][MATLAB Language Server]], matlabls, is used for code navigation, code completion,
go to definition, find references, and more. To use matlabls,

1. Install lsp-mode from MELPA

   #+begin_src emacs-lisp
     (require 'package)
     (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
   #+end_src

   then

   : M-x list-packages

   and click on lsp-mode and install it.

   You may also want to install =company= for completions.

2. Download and install the MATLAB language server

   Download the language server (clone or unzip):
   - git clone https://github.com/mathworks/MATLAB-language-server.git
   or
   - Download zip from https://github.com/mathworks/MATLAB-language-server and unzip.

   In the downloaded directory,
    #+begin_src bash
      npm install
      npm run compile
      npm run package  # optional JavaScript minimization

      # Install by copying built items into an install directory, e.g. /usr/local/apps/matlabls
      cp -r ./out/ /usr/local/apps/matlabls/out/
      cp -r ./matlab/ /usr/local/apps/matlabls/matlab/
    #+end_src

    In Emacs:
    
    : M-: (require 'lsp-matlab)
    : M-x customize-variable RET lsp-clients-matlab-server RET

    and set to your install directory, e.g. =/usr/local/apps/matlabls=

3. Tell lsp-mode where MATLAB is if MATLAB not on the PATH (~which matlab~ does not find MATLAB).

   In Emacs:

    : M-: (require 'lsp-matlab)
    : M-x customize-variable RET lsp-clients-matlab-install-path RET

   and set to your MATLAB installation e.g. =/usr/local/MATLAB/R2025a=

4. Activate lsp-mode when you open *.m files.

   Add to your ~/.emacs

   #+begin_example
     (add-hook 'matlab-mode-hook 'lsp)
   #+end_example

5. After loading a ~*.m~ file, the MATLAB language server will run MATLAB in the "background" and
   use that MATLAB for language server features such as ~xref-find-definitions~.  It can take a
   while for this background MATLAB to start.  After it starts, the supported language server
   features will work.  See https://github.com/mathworks/MATLAB-language-server for features
   supported.

   Some lsp features:

   : M-.   Find the definition of the identifier at point (xref-find-definitions)
   : M-?   Find references to the identifier at point (xref-find-references)
   : M-,   Go back to the previous position in xref history (xref-go-back)
