% -*- matlab-ts -*-

% t-utils-test-indent: no-line-by-line-indent - "} ..." is not handled correctly

someFcn(...
    'arg1', ...
    ... comment1
    '-foo1', ...
    {
      ... comment 2
      {'foo2', ...
       '-foo3', ...
       @(f)cmd([a '/' b 'c'], 'foo4', 'on'), ...
       '-foo5', {'x'}, ...
      } ...
      ...
      , ... comment
      {'foo', ...
       'bar'} ...
    });

function someFcn(varargin)
    disp(varargin);
end
