% -*- matlab-ts -*-
var_a = my_function(1, 2, 3);

var_b = my_function(1, ...
                    2, ...
                    3);

my_struct.var_c = my_function( ...
    1, ...
    2, ...
    3);

my_other_function(1, ...
                  2, ...
                  3);

% some extra spaces after a function call
my_other_function  ( ...
    1, ...
    2, ...
    3);
