% -*- matlab-ts -*-

% t-utils-test-indent: no-line-by-line-indent - continued "fcn_call(arg1, ..."
% isn't identified as a function call, so indenting line by line fails on this.

function indent_if_continued

    if condition1 || ...
       condition2 || ...
       fcn_call(arg1, ...
                arg2)

        line_in_if();

    elseif condition1 + condition2 == ...
           2770000 || ...
           fcn_call(arg1, ...
                    arg2)
        line_in_if();
    elseif (condition2 || ...
            (condition3 && ...
             condition4))
        disp('hello')
    elseif ...
        condition2 || ...
        (condition3 && ...
         condition4)

        disp('hello')
    else ...


    end

    if  a


    end

    if    ...
        foo + ...
        bar2 == 10

    end

end
