% -*- matlab-ts -*-

function indent_parens(inputArgument1)
    if ((someNamespace.getStartValue(((inputArgument1 + someOtherFunction(b)) * 2 - ...
                                      offset))) > ...
        2 * (someOtherLongFunctionInANamespaceThatGetsEndValue.myFcn(inputArgument1, ...
                                                                     'end') + ...
             100))
        disp('here')
    end
end
