% -*- matlab-ts -*-

data = struct(...
    'f', f, ...
    'm', struct('id', 1, 'other', 'two'), ...
    't', 'xyz', ...
    'input', ['[' text ']']);

data = struct('f', f, ...
              'm', struct('id', 1, 'other', 'two'), ...
              't', 'xyz', ...
              'input', ['[' text ']']);
