% -*- matlab-ts -*-
function a = indent_cont_statements

    a = ...
        1;

    a =     ...
        1 + ...
        2 + ...
        2;

    a = 2 * ...
        1;

    a = (       ...
         1 + 2);

    a = (  ...
         1 ...
        );
    
    a = 2 *  ...
        (    ...
         3 + ...
         4 + (    ...
              5 * ...
              6   ...
             )    ...
        ); ...
    
    a = 1 + 2;

    % The matlab-tree-sitter, by design for simplicity treats "..." as comments so the following
    % is an error in MATLAB, but doesn't generate a parse error and indents the same as if
    % the ellipsis (...) were present.
    a =
        1 +
        2;


end
