% -*- matlab-ts -*-

% See https://github.com/acristoffers/tree-sitter-matlab/issues/75
% https://www.mathworks.com/help/matlab/matlab_prog/command-vs-function-syntax.html

c1 ...
    = ...
    { ...
      'b'; ...
    };

c2 = ...
    { ...
      'b'; ...
    };
