% -*- matlab-ts -*-
function ...
    [    ...
     a,  ... comment about a
     b   ... comment about b
    ]    ...
    = indent_ellipsis ...
    (   ...
     c, ...  comment about c
     d, ...  comment about d
     e  ...  comment about e
    )

    a =     ...
        1 + ...
        (   ...
         c ...
         * ...
         d ...
        );

    b = [ ...
          1 + ...
          2 + ...
          3   ...
        ];

end
